# provider-kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: provider-k8s-base
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane
  interval: 1m0s
  path: ./kustomize/crossplane/providers/kubernetes/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: provider-k8s-with-config
  namespace: flux-system
spec:
  dependsOn:
    - name: provider-k8s-base
    - name: export-sa
  interval: 1m0s
  path: ./kustomize/crossplane/providers/kubernetes/with-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane

# provider-aws
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: provider-aws-base
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane
  interval: 1m0s
  path: ./kustomize/crossplane/providers/aws/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: provider-aws-with-config
  namespace: flux-system
spec:
  dependsOn:
    - name: provider-aws-base
  interval: 1m0s
  path: ./kustomize/crossplane/providers/aws/with-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane

# provider-jet-aws
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: provider-jet-aws-base
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane
  interval: 1m0s
  path: ./kustomize/crossplane/providers/jet-aws/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: provider-jet-aws-with-config
  namespace: flux-system
spec:
  dependsOn:
    - name: provider-jet-aws-base
  interval: 1m0s
  path: ./kustomize/crossplane/providers/jet-aws/with-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane
