# k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mock-cloud
  namespace: flux-system
spec:
  dependsOn:
    - name: provider-k8s-with-config
  interval: 1m0s
  path: ./kustomize/crossplane/resources/mock-cloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane

# aws
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws
  namespace: flux-system
spec:
  dependsOn:
    - name: provider-aws-with-config
  interval: 1m0s
  path: ./kustomize/crossplane/resources/aws
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane

# jet-aws
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jet-aws
  namespace: flux-system
spec:
  dependsOn:
    - name: provider-jet-aws-with-config
  interval: 1m0s
  path: ./kustomize/crossplane/resources/jet-aws
  prune: true
  sourceRef:
    kind: GitRepository
    name: taste-crossplane
