apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: this-new-sa
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: this-new-sa
        namespace: mock-cloud
        annotations:
          from: template
  providerConfigRef:
    name: kubernetes-provider
