apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: provide

configMapGenerator:
- name: files
  files:
  - job/export-creds.sh
generatorOptions:
  disableNameSuffixHash: true
resources:
- ./namespace.yaml
- ./serviceaccount.yaml
- ./clusterrolebinding.yaml
- ./job.yaml

