# crossplane
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-repo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/kustomize/external-repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-repo-example

