apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: mock-cloud-crossplane
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: mock-cloud
        annotations:
          0_created-by: crossplane
          0_how: you asked Crossplane and it listend to it
          1_extra1: even though this is just a Namespace in Kubernetes,
          1_extra2: imagine IAMUser in AWS or GCE instance in GCP
          1_extra3: infrastructure management becomes as simple as creating/updating a Kubernetes resource
          1_extra4: not only that, any deviation from the source of truth (Crossplane)
          1_extra5: will be caught and corrected (contious reconciliation)
  providerConfigRef:
    name: kubernetes-provider
