# use this to prevent this level of directory to be too big
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-include-self
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/local/self
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-include-external
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/local/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
